require("dotenv").config();
const express = require("express");
const path = require("path");
const router = require("./router");
const app = express();
app.use(express.json());
app.use("/",express.static(path.join(__dirname,"/client/build")));
app.use(router);
const port = process.env.PORT || 5000;
app.listen(port);